hyper:
  seed: 42
  epochs: 1
  lr: 0.00003
  train_batch_size: 1
  val_batch_size: 2
  grad_accumulation: 2
model:
  predict_with_generate: True
  generation_max_new_tokens: 300
  generation_num_beams: 1
eval:
  eval_strategy: "steps"
  eval_steps: 100000000
  metric: "task_acc"
save:
  save_strategy: "steps"
  save_steps: 50
logging[[]:
  logging_step: 1
